name: Raspberry Pi 4 Yocto Build

on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 600  # 최대 10시간
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone Yocto sources
        run: |
          git clone -b kirkstone https://git.yoctoproject.org/poky
          git clone -b kirkstone https://github.com/openembedded/meta-openembedded.git
          git clone -b kirkstone https://github.com/agherzan/meta-raspberrypi.git

      - name: Cache DL_DIR and SSTATE_DIR
        uses: actions/cache@v3
        with:
          path: |
            build/downloads
            build/sstate-cache
          key: yocto-cache-${{ runner.os }}-${{ hashFiles('**/conf/local.conf') }}
          restore-keys: |
            yocto-cache-${{ runner.os }}-

      - name: Setup and build Yocto image
        run: |
          source poky/oe-init-build-env build
          bitbake-layers add-layer ../meta-openembedded/meta-oe
          bitbake-layers add-layer ../meta-openembedded/meta-python
          bitbake-layers add-layer ../meta-openembedded/meta-networking
          bitbake-layers add-layer ../meta-raspberrypi
          echo 'MACHINE = "raspberrypi4"' >> conf/local.conf
          echo 'IMAGE_FSTYPES = "wic"' >> conf/local.conf
          echo 'DL_DIR ?= "${TOPDIR}/../downloads"' >> conf/local.conf
          echo 'SSTATE_DIR ?= "${TOPDIR}/../sstate-cache"' >> conf/local.conf
          bitbake core-image-minimal

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberrypi4-wic
          path: build/tmp/deploy/images/raspberrypi4/*.wic

